language: python
python: '2.7'
sudo: required
env:
  #matrix:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=1.6.1
  - ANSIBLE_VERSION=1.6.2
  - ANSIBLE_VERSION=1.6.3
  - ANSIBLE_VERSION=1.6.4
  - ANSIBLE_VERSION=1.6.5
  - ANSIBLE_VERSION=1.6.6
  - ANSIBLE_VERSION=1.6.7
  - ANSIBLE_VERSION=1.6.8
  - ANSIBLE_VERSION=1.6.9
  - ANSIBLE_VERSION=1.6.10
  - ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.7.1
  - ANSIBLE_VERSION=1.7.2
  - ANSIBLE_VERSION=1.8
  - ANSIBLE_VERSION=1.8.1
  - ANSIBLE_VERSION=1.8.2
  - ANSIBLE_VERSION=1.8.3
  - ANSIBLE_VERSION=1.8.4
  - ANSIBLE_VERSION=1.9.0.1
  - ANSIBLE_VERSION=1.9.1
  - ANSIBLE_VERSION=1.9.2
  - ANSIBLE_VERSION=1.9.3
install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install -U ansible; else pip  install -U ansible==$ANSIBLE_VERSION; fi
- printf "[defaults]\nroles_path = ../" > ansible.cfg
script:
 - ansible-playbook -i tests/test-inventory tests/test.yml --syntax-check
 # See the output
 - ansible-playbook -i tests/test-inventory tests/test.yml --connection=local --sudo

 # Run the role/playbook again, checking to make sure it's idempotent.
 - >
    ansible-playbook -i tests/test-inventory tests/test.yml --connection=local --sudo | grep -q 'changed=0.*failed=0'   && (echo 'Idempotence test: pass' && exit 0)    || (echo 'Idempotence test: fail' && exit 1)
notifications:
  email: false