---
# tasks file for ansible-hugo
#################################################
#   Valeriy Solovyov (weldpua2008@gmail.com)
#   Licenses: MIT  BSD
#   19.10.2015
#################################################
- set_fact:
     hugo_arch_extention: "amd64"
  when: ansible_architecture == "x86_64"
  tags:
    - hugo

- set_fact:
     hugo_arch_extention: "i386"
  when: ansible_architecture == "i386"
  tags:
    - hugo

- name: Include OS-specific variables.
  include_vars: "{{ item  }}"
  with_first_found:
   - "../vars/{{ ansible_distribution }}.yml"
   - "../vars/{{ ansible_os_family }}.yml"
   - "../vars/default.yml"
  tags:
    - hugo





#- include: install-debian.yml
#  when: "ansible_os_family == 'Debian'"
#  tags:
#    - hugo

- include: install-linux-from-source.yml
  when: "ansible_os_family in ['RedHat', 'Debian', 'Suse', 'Gentoo','Archlinux', 'Mandrake', 'Alpine', 'OtherLinux','OracleLinux']"
  tags:
    - hugo


#- include: install-centos.yml
#  when: "ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'"
#  tags:
#    - hugo
#
#
#- include: install-fedora.yml
#  when: "ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'"
#  tags:
#    - hugo
#
#- include: install-suse.yml
#  when: ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'
#  tags:
#    - hugo